version: '3.8'
services:
  one-frame-api:
    image: paidyinc/one-frame
    restart: always
    ports:
      - '9090:8080'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
volumes:
  db:
    driver: local