version: '3.8'
services:
#  forexapplication:
#    build: .
#    container_name: forexapplication
#    restart: always
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgresdb
#      - one-frame-application
#    links:
#      - one-frame-application
#      - postgresdb
  postgresdb:
    image: postgres:14
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
  one-frame-application:
    image: paidyinc/one-frame
    container_name: one-frame-application
    restart: always
    ports:
      - '9090:8080'
volumes:
  db:
    driver: local